#!/bin/sh

#**************************************************************************
#*                                                                        *
#*                                 OCaml                                  *
#*                                                                        *
#*            Xavier Leroy, projet Cristal, INRIA Rocquencourt            *
#*                                                                        *
#*   Copyright 1995 Institut National de Recherche en Informatique et     *
#*     en Automatique.                                                    *
#*                                                                        *
#*   All rights reserved.  This file is distributed under the terms of    *
#*   the GNU Lesser General Public License version 2.1, with the          *
#*   special exception on linking described in the file LICENSE.          *
#*                                                                        *
#**************************************************************************

if test "$EMSCRIPTEN"; then
  cmd="$cc $cflags -v -o tst.js $* $ldflags $cclibs"
else
  cmd="$cc $cflags -v -o tst $* $ldflags $cclibs"
fi

if $verbose; then
  echo "runtest: $cmd" >&2
  $cmd || echo 100
else
  echo "runtest: $cmd" >&2
  $cmd 2> /dev/null || exit 100
fi

if test "$EMSCRIPTEN"; then
  exec node ./tst.js
else
  exec ./tst
fi


